=== texx94/SER_Labo1/fse.dtd
<!ELEMENT fse (tournoi*, joueur*)>
<!ELEMENT tournoi (nom,partie*)>
<!ATTLIST tournoi vainqueur IDREF #REQUIRED>
<!ELEMENT partie (arbitre,date,heure,blanc,noir,score,coups*)>
<!ELEMENT blanc EMPTY>
<!ELEMENT noir EMPTY>
<!ATTLIST blanc joueur IDREF #REQUIRED>
<!ATTLIST noir joueur IDREF #REQUIRED>
<!ELEMENT joueur (nom,prenom,elo)>
<!ATTLIST joueur id_fse ID #REQUIRED>
<!ELEMENT arbitre (nom,prenom)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT heure (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT score (#PCDATA)>
<!ELEMENT camp (#PCDATA)>
<!ELEMENT elo (#PCDATA)>
<!ELEMENT coups (deplacement|elimination|promotion|echec|roque)>
<!ELEMENT deplacement (type_piece,dest_case,dep_case?)>
<!ELEMENT roque (type_roque)>
<!ELEMENT type_roque (#PCDATA)>
<!ELEMENT type_piece (#PCDATA)>
<!ELEMENT dest_case (#PCDATA)>
<!ELEMENT dep_case (#PCDATA)>
<!ELEMENT elimination (deplacement,piece_elim)>
<!ELEMENT promotion (deplacement,piece_rempl)>
<!ELEMENT echec (deplacement,type_echec)>
<!ELEMENT piece_elim (#PCDATA)>
<!ELEMENT piece_rempl (#PCDATA)>
<!ELEMENT type_echec (#PCDATA)>

=== texx94/SER_Labo1/fse.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE fse SYSTEM "fse.dtd">
<fse>
    <tournoi vainqueur="J1">
        <nom>Junior</nom>
        <partie joueurs="J1 J2">
            <arbitre>
                <nom>Nemo</nom>
                <prenom>Doris</prenom>
            </arbitre>
            <date>12.03.2019</date>
            <heure>13:30</heure>
            <score>1-0</score>
            <coups>
                <deplacement>
                    <type_piece>pion</type_piece>
                    <dest_case>e4</dest_case>
                    <dep_case>e2</dep_case>
                </deplacement>
            </coups>
            <coups>
                <deplacement>
                    <type_piece>pion</type_piece>
                    <dest_case>f5</dest_case>
                    <dep_case>f7</dep_case>
                </deplacement>
            </coups>
            <coups>
                <elimination>
                    <deplacement>
                        <type_piece>pion</type_piece>
                        <dest_case>f5</dest_case>
                        <dep_case>e4</dep_case>
                    </deplacement>
                    <piece_elim>pion</piece_elim>
                </elimination>
            </coups>
            <coups>
                <deplacement>
                    <type_piece>pion</type_piece>
                    <dest_case>g5</dest_case>
                    <dep_case>g7</dep_case>
                </deplacement>
            </coups>
            <coups>
                <echec>
                    <deplacement>
                        <type_piece>dame</type_piece>
                        <dest_case>h5</dest_case>
                        <dep_case>d1</dep_case>
                    </deplacement>
                    <type_echec>echec et mat</type_echec>
                </echec>
            </coups>
        </partie>
        <partie joueurs="J1 J2">
            <arbitre>
                <nom>Nemo</nom>
                <prenom>Doris</prenom>
            </arbitre>
            <date>12.03.2019</date>
            <heure>13:40</heure>
            <score>1-0</score>
            <coups>
                <deplacement>
                    <type_piece>pion</type_piece>
                    <dest_case>e4</dest_case>
                    <dep_case>e2</dep_case>
                </deplacement>
            </coups>
            <coups>
                <deplacement>
                    <type_piece>pion</type_piece>
                    <dest_case>f5</dest_case>
                    <dep_case>f7</dep_case>
                </deplacement>
            </coups>
            <coups>
                <elimination>
                    <deplacement>
                        <type_piece>pion</type_piece>
                        <dest_case>f5</dest_case>
                        <dep_case>e4</dep_case>
                    </deplacement>
                    <piece_elim>pion</piece_elim>
                </elimination>
            </coups>
            <coups>
                <deplacement>
                    <type_piece>pion</type_piece>
                    <dest_case>g5</dest_case>
                    <dep_case>g7</dep_case>
                </deplacement>
            </coups>
            <coups>
                <echec>
                    <deplacement>
                        <type_piece>dame</type_piece>
                        <dest_case>h5</dest_case>
                        <dep_case>d1</dep_case>
                    </deplacement>
                    <type_echec>echec et mat</type_echec>
                </echec>
            </coups>
        </partie>
    </tournoi>
    <tournoi vainqueur="J1">
        <nom>Master</nom>
        <partie joueurs="J1 J2">
            <arbitre>
                <nom>Nemo</nom>
                <prenom>Doris</prenom>
            </arbitre>
            <date>12.03.2019</date>
            <heure>13:30</heure>
            <score>1-0</score>
            <coups>
                <deplacement>
                    <type_piece>pion</type_piece>
                    <dest_case>e4</dest_case>
                    <dep_case>e2</dep_case>
                </deplacement>
            </coups>
            <coups>
                <deplacement>
                    <type_piece>pion</type_piece>
                    <dest_case>f5</dest_case>
                    <dep_case>f7</dep_case>
                </deplacement>
            </coups>
            <coups>
                <elimination>
                    <deplacement>
                        <type_piece>pion</type_piece>
                        <dest_case>f5</dest_case>
                        <dep_case>e4</dep_case>
                    </deplacement>
                    <piece_elim>pion</piece_elim>
                </elimination>
            </coups>
            <coups>
                <deplacement>
                    <type_piece>pion</type_piece>
                    <dest_case>g5</dest_case>
                    <dep_case>g7</dep_case>
                </deplacement>
            </coups>
            <coups>
                <echec>
                    <deplacement>
                        <type_piece>dame</type_piece>
                        <dest_case>h5</dest_case>
                        <dep_case>d1</dep_case>
                    </deplacement>
                    <type_echec>echec et mat</type_echec>
                </echec>
            </coups>
        </partie>
        <partie joueurs="J1 J2">
            <arbitre>
                <nom>Nemo</nom>
                <prenom>Doris</prenom>
            </arbitre>
            <date>12.03.2019</date>
            <heure>13:40</heure>
            <score>1-0</score>
            <coups>
                <deplacement>
                    <type_piece>pion</type_piece>
                    <dest_case>e4</dest_case>
                    <dep_case>e2</dep_case>
                </deplacement>
            </coups>
            <coups>
                <deplacement>
                    <type_piece>pion</type_piece>
                    <dest_case>f5</dest_case>
                    <dep_case>f7</dep_case>
                </deplacement>
            </coups>
            <coups>
                <elimination>
                    <deplacement>
                        <type_piece>pion</type_piece>
                        <dest_case>f5</dest_case>
                        <dep_case>e4</dep_case>
                    </deplacement>
                    <piece_elim>pion</piece_elim>
                </elimination>
            </coups>
            <coups>
                <deplacement>
                    <type_piece>pion</type_piece>
                    <dest_case>g5</dest_case>
                    <dep_case>g7</dep_case>
                </deplacement>
            </coups>
            <coups>
                <echec>
                    <deplacement>
                        <type_piece>dame</type_piece>
                        <dest_case>h5</dest_case>
                        <dep_case>d1</dep_case>
                    </deplacement>
                    <type_echec>echecetmat</type_echec>
                </echec>
            </coups>
        </partie>
    </tournoi>
    <joueur id_fse="J1">
        <nom>Bob</nom>
        <prenom>L'eponge</prenom>
        <camp>Blanc</camp>
        <elo>2000</elo>
    </joueur>
    <joueur id_fse="J2">
        <nom>Cartman</nom>
        <prenom>Eric</prenom>
        <camp>Noir</camp>
        <elo>2000</elo>
    </joueur>
</fse>
